#!/usr/bin/env python3
"""
Take the Configurator's own tab icons.

    python3 tools/gen_icons.py <configurator-checkout> data/icons-2.3.js

The viewer drew a rounded square in place of an icon, which reads as an empty
checkbox down the whole rail and is the first thing that looks unlike the
Configurator. Its icons are single-colour SVGs, so each one is emitted once and
used as a CSS mask over `currentColor`: the icon then follows the tab's own
colour, grey normally and dark on the selected tab, the way the Configurator
swaps its grey and white files.

Two files decide which icon a tab gets, and both are read rather than guessed:
src/main.html names a class per tab (`tab_mixer` -> `ic_adjust`) and
src/css/main.css points that class at a file.

The tabs the viewer adds are mapped here, since the Configurator has no tab to
copy for them.

The Configurator is GPL-3.0; see LICENSE and NOTICE.
"""

import json
import os
import re
import sys
from urllib.parse import quote

# The viewer's own tabs, given an icon the Configurator uses elsewhere.
EXTRA = {
    'rescue': 'ic_failsafe',
    'osd': 'ic_log',
    'board': 'ic_advanced',
    'all': 'ic_log',
    'ports': 'ic_ports',
}

# `tab_auxiliary` in the Configurator is `modes` here; the rest match by name.
RENAMED = {'auxiliary': 'modes', 'led_strip': 'ledstrip'}


def read(path):
    with open(path, encoding='utf-8', errors='replace') as fh:
        return fh.read()


def minify(svg):
    """Drop what a mask does not need: comments, the XML prologue, whitespace."""
    svg = re.sub(r'<\?xml.*?\?>', '', svg, flags=re.S)
    svg = re.sub(r'<!--.*?-->', '', svg, flags=re.S)
    svg = re.sub(r'\s+', ' ', svg).strip()
    return svg


def viewer_tabs(repo):
    """The tab ids in js/schema.js, so no icon is carried that nothing shows."""
    path = os.path.join(repo, 'js', 'schema.js')
    if not os.path.exists(path):
        return set()
    text = read(path)
    m = re.search(r'var TABS = \[(.*?)\n\s*\];', text, re.S)
    if not m:
        return set()
    return set(re.findall(r"id:\s*'([^']+)'", m.group(1)))


def main():
    if len(sys.argv) != 3:
        raise SystemExit(__doc__)
    cfg, out_path = sys.argv[1], sys.argv[2]

    main_html = read(os.path.join(cfg, 'src', 'main.html'))
    main_css = read(os.path.join(cfg, 'src', 'css', 'main.css'))

    files = {}
    for m in re.finditer(r'\.(ic_\w+)\s*\{\s*background-image:\s*url\(([^)]*_grey\.svg)\)',
                         main_css):
        files[m.group(1)] = m.group(2).split('/')[-1]

    tab_icon = {}
    for m in re.finditer(r'class="tab_(\w+)"[^>]*>\s*<a[^>]*class="tabicon (ic_\w+)"',
                         main_html):
        tab = RENAMED.get(m.group(1), m.group(1))
        tab_icon[tab] = m.group(2)
    tab_icon.update(EXTRA)

    # Only the tabs the viewer has; the Configurator's own extras (the flasher,
    # the landing page, the options screen) have no home here.
    wanted = viewer_tabs(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    if wanted:
        tab_icon = {k: v for k, v in tab_icon.items() if k in wanted}
        for tab in sorted(wanted - set(tab_icon)):
            print('  ! the viewer has a %s tab with no icon' % tab, file=sys.stderr)

    icons = {}
    missing = []
    for tab, ic in sorted(tab_icon.items()):
        name = files.get(ic)
        path = os.path.join(cfg, 'src', 'images', 'icons', name) if name else None
        if not path or not os.path.exists(path):
            missing.append('%s (%s)' % (tab, ic))
            continue
        # URL-encoded rather than base64: a fifth smaller, and the result is
        # still readable, which matters in a file that ships inlined.
        # `#` must be escaped: inside a data URI it would start a fragment and
        # cut the SVG off at the first fill colour.
        data = quote(minify(read(path)), safe="/:;=,()-+*. '")
        icons[tab] = 'data:image/svg+xml,' + data

    print('%d tabs given the Configurator\'s own icon' % len(icons))
    for tab in sorted(icons):
        print('   %-14s %s' % (tab, files[tab_icon[tab]]))
    for entry in missing:
        print('  ! no icon found for %s' % entry, file=sys.stderr)

    with open(out_path, 'w', encoding='utf-8') as fh:
        fh.write('// Generated by tools/gen_icons.py from the Rotorflight\n'
                 '// Configurator (GPL-3.0; see NOTICE). Do not edit by hand.\n'
                 '// One single-colour SVG per tab, used as a CSS mask.\n')
        fh.write('window.RF_ICONS = %s;\n'
                 % json.dumps(icons, separators=(',', ':'), sort_keys=True))
    print('wrote %s (%d bytes)' % (out_path, os.path.getsize(out_path)))


if __name__ == '__main__':
    main()
